In [74]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.svm import SVR
from sklearn.metrics import root_mean_squared_error, r2_score

In [50]:
df=pd.read_csv(r"diabetes_012_health_indicators_BRFSS2015.csv")

In [51]:
df= df.iloc[0:1000, :]

In [52]:
df.shape[0]

1000

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Diabetes_012          1000 non-null   float64
 1   HighBP                1000 non-null   float64
 2   HighChol              1000 non-null   float64
 3   CholCheck             1000 non-null   float64
 4   BMI                   1000 non-null   float64
 5   Smoker                1000 non-null   float64
 6   Stroke                1000 non-null   float64
 7   HeartDiseaseorAttack  1000 non-null   float64
 8   PhysActivity          1000 non-null   float64
 9   Fruits                1000 non-null   float64
 10  Veggies               1000 non-null   float64
 11  HvyAlcoholConsump     1000 non-null   float64
 12  AnyHealthcare         1000 non-null   float64
 13  NoDocbcCost           1000 non-null   float64
 14  GenHlth               1000 non-null   float64
 15  MentHlth              1000 non-null   float64
 16  PhysHlth              1000 non-null   float64
 17  DiffWalk              1000 non-null   float64
 18  Sex                   1000 non-null   float64
 19  Age                   1000 non-null   float64
 20  Education             1000 non-null   float64
 21  Income                1000 non-null   float64
dtypes: float64(22)
memory usage: 172.0 KB

In [54]:
df.describe()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.463000,0.591000,0.530000,0.983000,29.217000,0.446000,0.066000,0.134000,0.636000,0.578000,...,0.95800,0.103000,2.883000,4.123000,5.766000,0.305000,0.348000,9.069000,4.769000,5.315000
std,0.831458,0.491895,0.499349,0.129336,6.218085,0.497324,0.248406,0.340823,0.481389,0.494126,...,0.20069,0.304111,1.099327,8.392515,9.929141,0.460638,0.476574,2.666712,1.052971,2.231312
min,0.000000,0.000000,0.000000,0.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.00000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,4.000000,3.000000
50%,0.000000,1.000000,1.000000,1.000000,28.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.00000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,9.000000,5.000000,6.000000
75%,0.000000,1.000000,1.000000,1.000000,32.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.00000,0.000000,4.000000,3.000000,7.000000,1.000000,1.000000,11.000000,6.000000,7.000000
max,2.000000,1.000000,1.000000,1.000000,59.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.00000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [55]:
df.corr(numeric_only=True)

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
Diabetes_012,1.000000,0.240753,0.119608,0.073267,0.192749,0.023002,0.181464,0.151743,-0.116212,-0.033170,...,0.002675,0.028943,0.248783,0.005315,0.098618,0.213751,-0.002839,0.172481,-0.082375,-0.146675
HighBP,0.240753,1.000000,0.235429,0.110879,0.168136,0.005786,0.122833,0.195878,-0.079795,-0.018936,...,0.018475,0.000850,0.333474,0.073060,0.152339,0.268357,-0.007122,0.319148,-0.163265,-0.197146
HighChol,0.119608,0.235429,1.000000,0.093151,0.037716,0.087146,0.088930,0.164570,-0.091946,-0.005436,...,0.022574,0.022478,0.220661,0.095497,0.081165,0.145133,0.036006,0.191259,-0.058198,-0.096084
CholCheck,0.073267,0.110879,0.093151,1.000000,0.059358,-0.006505,0.034958,0.051730,0.061288,0.028601,...,0.126724,-0.108136,0.014158,-0.051559,0.014048,0.036712,0.047356,0.096277,0.029937,0.018574
BMI,0.192749,0.168136,0.037716,0.059358,1.000000,-0.045571,0.015345,0.014606,-0.082269,-0.046727,...,-0.042422,0.103567,0.205801,0.072186,0.066616,0.207525,-0.003552,-0.135704,-0.037896,-0.058897
Smoker,0.023002,0.005786,0.087146,-0.006505,-0.045571,1.000000,0.036981,0.095884,-0.069642,-0.096898,...,0.017371,0.040122,0.073570,0.083974,0.026224,0.043564,0.252527,0.026588,-0.053473,0.004068
Stroke,0.181464,0.122833,0.088930,0.034958,0.015345,0.036981,1.000000,0.191019,-0.075138,0.006948,...,-0.024657,0.108682,0.156602,0.010987,0.108135,0.200068,-0.008185,0.097385,-0.083252,-0.135069
HeartDiseaseorAttack,0.151743,0.195878,0.164570,0.051730,0.014606,0.095884,0.191019,1.000000,-0.074580,-0.002687,...,0.053094,0.059858,0.204857,0.070522,0.176401,0.198484,0.088547,0.202380,-0.072649,-0.093732
PhysActivity,-0.116212,-0.079795,-0.091946,0.061288,-0.082269,-0.069642,-0.075138,-0.074580,1.000000,0.077398,...,0.017739,-0.058175,-0.303756,-0.138063,-0.249251,-0.266246,0.029111,-0.038118,0.100549,0.103126
Fruits,-0.033170,-0.018936,-0.005436,0.028601,-0.046727,-0.096898,0.006948,-0.002687,0.077398,1.000000,...,0.053257,-0.023541,-0.061500,-0.071955,-0.068501,-0.049651,-0.098380,0.066940,0.066409,0.003568
Veggies,-0.077115,0.006291,0.009381,-0.022605,0.014646,0.036868,-0.050477,-0.016019,0.094123,0.201167,...,0.039759,-0.031466,-0.095225,-0.042377,-0.047812,-0.087388,-0.022524,0.018447,0.210417,0.163461
HvyAlcoholConsump,-0.023279,0.031439,0.006589,-0.021111,-0.046165,0.118094,-0.001069,0.014329,0.015397,-0.022407,...,0.037451,-0.022646,-0.064971,-0.006062,-0.025433,-0.055829,0.038906,0.034334,0.066670,0.119615
AnyHealthcare,0.002675,0.018475,0.022574,0.126724,-0.042422,0.017371,-0.024657,0.053094,0.017739,0.053257,...,1.000000,-0.257074,-0.044981,-0.103312,0.007622,0.008771,0.006447,0.181238,0.115097,0.177108
NoDocbcCost,0.028943,0.000850,0.022478,-0.108136,0.103567,0.040122,0.108682,0.059858,-0.058175,-0.023541,...,-0.257074,1.000000,0.200762,0.255846,0.187666,0.189968,-0.067990,-0.161827,-0.075671,-0.242584
GenHlth,0.248783,0.333474,0.220661,0.014158,0.205801,0.073570,0.156602,0.204857,-0.303756,-0.061500,...,-0.044981,0.200762,1.000000,0.315984,0.570099,0.489607,-0.050219,0.131143,-0.274150,-0.403652
MentHlth,0.005315,0.073060,0.095497,-0.051559,0.072186,0.083974,0.010987,0.070522,-0.138063,-0.071955,...,-0.103312,0.255846,0.315984,1.000000,0.359541,0.245074,-0.047753,-0.149364,-0.068823,-0.163663
PhysHlth,0.098618,0.152339,0.081165,0.014048,0.066616,0.026224,0.108135,0.176401,-0.249251,-0.068501,...,0.007622,0.187666,0.570099,0.359541,1.000000,0.484634,-0.013870,0.069566,-0.127535,-0.260079
DiffWalk,0.213751,0.268357,0.145133,0.036712,0.207525,0.043564,0.200068,0.198484,-0.266246,-0.049651,...,0.008771,0.189968,0.489607,0.245074,0.484634,1.000000,-0.069035,0.208575,-0.207500,-0.345808
Sex,-0.002839,-0.007122,0.036006,0.047356,-0.003552,0.252527,-0.008185,0.088547,0.029111,-0.098380,...,0.006447,-0.067990,-0.050219,-0.047753,-0.013870,-0.069035,1.000000,-0.024426,0.038674,0.192390
Age,0.172481,0.319148,0.191259,0.096277,-0.135704,0.026588,0.097385,0.202380,-0.038118,0.066940,...,0.181238,-0.161827,0.131143,-0.149364,0.069566,0.208575,-0.024426,1.000000,-0.139408,-0.142613
Education,-0.082375,-0.163265,-0.058198,0.029937,-0.037896,-0.053473,-0.083252,-0.072649,0.100549,0.066409,...,0.115097,-0.075671,-0.274150,-0.068823,-0.127535,-0.207500,0.038674,-0.139408,1.000000,0.477073
Income,-0.146675,-0.197146,-0.096084,0.018574,-0.058897,0.004068,-0.135069,-0.093732,0.103126,0.003568,...,0.177108,-0.242584,-0.403652,-0.163663,-0.260079,-0.345808,0.192390,-0.142613,0.477073,1.000000

In [56]:
df.columns

Index(['Diabetes_012', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [57]:
X=df.drop("Diabetes_012", axis=1)
y=df["Diabetes_012"]

In [58]:
X_train, X_test, y_train, y_test =train_test_split(X, y, random_state=42, test_size=0.2)

In [59]:
model = SVR()

In [60]:
param_grid={"kernel":["linear", "poly", "rbf", "sigmoid"]}

In [61]:
grid_search = GridSearchCV(model, param_grid, scoring="neg_root_mean_squared_error")

In [62]:
grid_search.fit(X_train, y_train)

GridSearchCV(estimator=SVR(),
             param_grid={'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='neg_root_mean_squared_error')

In [63]:
grid_search.cv_results_

{'mean_fit_time': array([0.25159163, 0.02516079, 0.03306236, 0.02871351]),
 'std_fit_time': array([0.03140456, 0.00313947, 0.00924181, 0.00623692]),
 'mean_score_time': array([0.00495429, 0.00527816, 0.01031003, 0.0183074 ]),
 'std_score_time': array([0.00141593, 0.00130066, 0.00117726, 0.01965313]),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'kernel': 'linear'},
  {'kernel': 'poly'},
  {'kernel': 'rbf'},
  {'kernel': 'sigmoid'}],
 'split0_test_score': array([-0.90406767, -0.8109108 , -0.82002366, -2.37566092]),
 'split1_test_score': array([-0.86593683, -0.85558345, -0.86115833, -2.19795284]),
 'split2_test_score': array([-0.87589504, -0.85617422, -0.86764771, -3.28644843]),
 'split3_test_score': array([-0.97844165, -0.9744454 , -0.97624115, -2.50556115]),
 'split4_test_score': array([-0.89582763, -0.88842961, -0.89367603, -2.83143793]),
 'mean_test_score': array([-0.90403376, -0.8771087 , -0.88374937, -2.63941226]),
 'std_test_score': array([0.03961575, 0.05456436, 0.05193044, 0.38416064]),
 'rank_test_score': array([3, 1, 2, 4], dtype=int32)}

In [78]:
model = SVR(kernel="rbf")

In [79]:
model.fit(X_train, y_train)

SVR()

In [80]:
y_pred = model.predict(X_test)

In [81]:
print("RMSE", root_mean_squared_error(y_test, y_pred))

RMSE 0.9659515778668715

In [82]:
print("R2_Square", r2_score(y_test, y_pred))

R2_Square -0.22872421502353735

In [83]:
import joblib

In [84]:
joblib.dump(model, "svr_model.pkl")

['svr_model.pkl']

In [86]:
model=joblib.load("svr_model.pkl")

In [87]:
model.predict(X.sample(1).to_numpy())

c:\Users\rohit\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

array([0.09018323])