In [7]:
import numpy as np
import pandas as pd

In [8]:
dataset=pd.read_csv("house_price_chandigarh_dataset.csv")

In [9]:
dataset.head()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,area,price,status,new/resale,price_negotiable,security_deposit,...,Lift(s),Full Power Backup,24 X 7 Security,Children's play area,Club House,Gymnasium,Swimming Pool,Sports Facility,Jogging Track,Landscaped Gardens
0,0,0,0,0,1300,2850000,NaN,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,1400,3600000,NaN,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2,2,2,2,1350,3690000,NaN,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,3,3,3,3,1200,10000000,NaN,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,4,4,4,4,1008,3090000,NaN,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056 entries, 0 to 1055
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0.3          1056 non-null   int64
 1   Unnamed: 0.2          1056 non-null   int64
 2   Unnamed: 0.1          1056 non-null   int64
 3   Unnamed: 0            1056 non-null   int64
 4   area                  1056 non-null   int64
 5   price                 1056 non-null   int64
 6   status                210 non-null    float64
 7   new/resale            1056 non-null   int64
 8   price_negotiable      1056 non-null   int64
 9   security_deposit      1056 non-null   int64
 10  furnished             1056 non-null   int64
 11  age of property       1056 non-null   int64
 12  Lift(s)               1056 non-null   int64
 13  Full Power Backup     1056 non-null   int64
 14  24 X 7 Security       1056 non-null   int64
 15  Children's play area  1056 non-null   int64
 16  Club House            1056 non-null   int64
 17  Gymnasium             1056 non-null   int64
 18  Swimming Pool         1056 non-null   int64
 19  Sports Facility       1056 non-null   int64
 20  Jogging Track         1056 non-null   int64
 21  Landscaped Gardens    1056 non-null   int64
dtypes: float64(1), int64(21)
memory usage: 181.6 KB

In [11]:
dataset.describe()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,area,price,status,new/resale,price_negotiable,security_deposit,...,Lift(s),Full Power Backup,24 X 7 Security,Children's play area,Club House,Gymnasium,Swimming Pool,Sports Facility,Jogging Track,Landscaped Gardens
count,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1.056000e+03,210.000000,1056.000000,1056.000000,1056.0,...,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000
mean,527.500000,527.500000,527.500000,527.500000,1320.814394,4.952882e+06,0.738095,0.889205,0.692235,1.0,...,0.332386,0.523674,0.574811,0.444129,0.317235,0.404356,0.291667,0.307765,0.344697,0.226326
std,304.985246,304.985246,304.985246,304.985246,621.300997,5.834945e+06,0.440722,0.314027,0.461788,0.0,...,0.471292,0.499676,0.494606,0.497104,0.465620,0.491000,0.454745,0.461788,0.475495,0.418651
min,0.000000,0.000000,0.000000,0.000000,460.000000,1.290000e+06,0.000000,0.000000,0.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,263.750000,263.750000,263.750000,263.750000,930.000000,2.580000e+06,0.000000,1.000000,0.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,527.500000,527.500000,527.500000,527.500000,1200.000000,3.590000e+06,1.000000,1.000000,1.000000,1.0,...,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,791.250000,791.250000,791.250000,791.250000,1620.000000,6.000000e+06,1.000000,1.000000,1.000000,1.0,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1055.000000,1055.000000,1055.000000,1055.000000,9000.000000,1.000000e+08,1.000000,1.000000,1.000000,1.0,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000