In [101]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import seaborn as sns

In [102]:
df=sns.load_dataset("tips")

In [103]:
df.sample(10)

     total_bill    tip     sex smoker   day    time  size
237       32.83   1.17    Male    Yes   Sat  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
36        16.31   2.00    Male     No   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
170       50.81  10.00    Male    Yes   Sat  Dinner     3
57        26.41   1.50  Female     No   Sat  Dinner     2
236       12.60   1.00    Male    Yes   Sat  Dinner     2
203       16.40   2.50  Female    Yes  Thur   Lunch     2
51        10.29   2.60  Female     No   Sun  Dinner     2

In [104]:
df_split=df[["total_bill","tip","size"]]

## Performing One Hot Encoding on "sex", "smoker", "time" columns

In [105]:
onehot_encoder=OneHotEncoder()

In [106]:
transformed_onehot=onehot_encoder.fit_transform(df[["sex","smoker","time"]]).toarray()

In [107]:
transformed_onehot=np.array(transformed_onehot,dtype="int")

In [108]:
col_names=onehot_encoder.get_feature_names_out(["sex","smoker","time"])

In [109]:
new_dataset=pd.DataFrame(transformed_onehot,columns=col_names)

In [110]:
transformed_dataset=pd.concat([df_split,new_dataset],axis=1)

## Performing Label Encoding on "day" column

In [111]:
label_encoder=LabelEncoder()

In [112]:
target=label_encoder.fit_transform(df["day"])

In [113]:
transformed_dataset["day"]=target

In [114]:
transformed_dataset.sample(10)

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,time_Dinner,time_Lunch,day
62,11.02,1.98,2,0,1,0,1,1,0,1
98,21.01,3.00,2,0,1,0,1,1,0,0
115,17.31,3.50,2,1,0,1,0,1,0,2
229,22.12,2.88,2,1,0,0,1,1,0,1
147,11.87,1.63,2,1,0,1,0,0,1,3
39,31.27,5.00,3,0,1,1,0,1,0,1
54,25.56,4.34,4,0,1,1,0,1,0,2
161,12.66,2.50,2,0,1,1,0,1,0,2
50,12.54,2.50,2,0,1,1,0,1,0,2
16,10.33,1.67,3,1,0,1,0,1,0,2