In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
dataset=pd.read_csv(r"C:\Users\rohit\Downloads\Housing.csv")

In [3]:
dataset.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [4]:
y=dataset[["price"]]
X=dataset.drop("price",axis=1)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
X_train.head(5)

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,6000,3,2,4,yes,no,no,no,yes,1,no,furnished
93,7200,3,2,1,yes,no,yes,no,yes,3,no,semi-furnished
335,3816,2,1,1,yes,no,yes,no,yes,2,no,furnished
412,2610,3,1,2,yes,no,yes,no,no,0,yes,unfurnished
471,3750,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [7]:
y_train.head(5)

       price
46   7525000
93   6300000
335  3920000
412  3430000
471  3010000

In [8]:
print("Training dataset size is: ",X_train.shape[0])
print("Test dataset size is: ",X_test.shape[0])

Training dataset size is:  436
Test dataset size is:  109